import { Geist, Geist_Mono } from "next/font/google";
import {Amiri} from "next/font/google";
import { Cairo } from "next/font/google";
import { Gulzar } from "next/font/google";
import { Scheherazade_New } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jameelNooriNastaleeq = Gulzar({
  variable: "--font-jameel-noori-nastaleeq",
  subsets: ["arabic"],
  weight: "400",
  display: "swap",
  fallback: ["serif"]
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jameelNooriNastaleeq.variable} antialiased`}
      >
        <Navbar />
        <main className="w-full flex flex-col min-h-screen">
          <div className="grow">
            {children}
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
